### ISSUE TITLE
raz: options without effect.

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#56] opened 2015-06-04 14:02 UTC
Option -f is without effect.
Only real image simple or double precision are produced.
raz -f should produce 1 byte image in fixed format, 
raz -f -o 2 should produce 2 byte image in fixed format
raz -f -o 4 should produce 4 byte image in fixed format

**Comment by dfroger** [comment] 2015-06-25 13:31
duplicate of #60

**Closed as completed by dfroger** 2015-06-25 13:31 UTC
